export default new Map([
  // File menu
  ['file.new-window', 'mod+N'],
  ['file.new-tab', 'mod+T'],
  ['file.open-file', 'mod+O'],
  ['file.open-folder', 'mod+shift+O'],
  ['file.save', 'mod+S'],
  ['file.save-as', 'mod+shift+S'],
  ['file.move-file', ''],
  ['file.rename-file', ''],
  ['file.print', ''],
  ['file.preferences', 'mod+,'],
  ['file.close-tab', 'mod+W'],
  ['file.close-window', 'mod+shift+W'],
  ['file.quit', 'mod+Q'],

  // Edit menu
  ['edit.undo', 'mod+z'],
  ['edit.redo', 'mod+z'],
  ['edit.cut', 'mod+x'],
  ['edit.copy', 'mod+c'],
  ['edit.paste', 'mod+v'],
  ['edit.copy-as-markdown', 'mod+shift+c'],
  ['edit.copy-as-html', ''],
  ['edit.paste-as-plaintext', 'mod+shift+v'],
  ['edit.select-all', 'mod+A'],
  ['edit.duplicate', 'mod+Alt+D'],
  ['edit.create-paragraph', 'mod+shift+N'],
  ['edit.delete-paragraph', 'mod+shift+D'],
  ['edit.find', 'mod+F'],
  ['edit.find-next', 'F3'],
  ['edit.find-previous', 'shift+F3'],
  ['edit.replace', 'mod+R'],
  ['edit.find-in-folder', 'mod+shift+F'],
  ['edit.screenshot', ''], // macOS only

  // Paragraph menu
  // NOTE: We cannot set a default value for heading size because `mod+Alt` is an alias
  //       to `AltGr` on Windows and `mod+shift+1` is mapped to the underlying character.
  ['paragraph.heading-1', ''],
  ['paragraph.heading-2', ''],
  ['paragraph.heading-3', ''],
  ['paragraph.heading-4', ''],
  ['paragraph.heading-5', ''],
  ['paragraph.heading-6', ''],
  ['paragraph.upgrade-heading', 'mod+Plus'],
  ['paragraph.degrade-heading', 'mod+-'],
  ['paragraph.table', 'mod+shift+T'],
  ['paragraph.code-fence', 'mod+shift+K'],
  ['paragraph.quote-block', 'mod+shift+Q'],
  ['paragraph.math-formula', 'mod+Alt+N'],
  ['paragraph.html-block', 'mod+Alt+H'],
  ['paragraph.order-list', 'mod+G'],
  ['paragraph.bullet-list', 'mod+H'],
  ['paragraph.task-list', 'mod+Alt+x'],
  ['paragraph.loose-list-item', 'mod+Alt+L'],
  ['paragraph.paragraph', 'mod+shift+0'],
  ['paragraph.horizontal-line', 'mod+shift+U'],
  ['paragraph.front-matter', 'mod+Alt+Y'],

  // Format menu
  ['format.strong', 'mod+B'],
  ['format.emphasis', 'mod+I'],
  ['format.underline', 'mod+U'],
  ['format.superscript', ''],
  ['format.subscript', ''],
  ['format.highlight', 'mod+shift+H'],
  ['format.inline-code', 'mod+`'],
  ['format.inline-math', 'mod+shift+M'],
  ['format.strike', 'mod+D'],
  ['format.hyperlink', 'mod+L'],
  ['format.image', 'mod+shift+I'],
  ['format.clear-format', 'mod+shift+R'],

  // Window menu
  ['window.minimize', 'mod+M'],
  ['window.toggle-always-on-top', ''],
  ['window.zoom-in', ''],
  ['window.zoom-out', ''],
  ['window.toggle-full-screen', 'F11'],

  // View menu
  ['view.command-palette', 'mod+shift+P'],
  ['view.source-code-mode', 'mod+E'],
  ['view.typewriter-mode', 'mod+shift+G'],
  ['view.focus-mode', 'mod+shift+J'],
  ['view.toggle-sidebar', 'mod+J'],
  ['view.toggle-toc', 'mod+K'],
  ['view.toggle-tabbar', 'mod+shift+B'],
  ['view.toggle-dev-tools', 'mod+Alt+I'],
  ['view.dev-reload', 'mod+F5'],
  ['view.reload-images', 'F5'],

  // ======== Not included in application menu ========================
  ['tabs.cycle-forward', 'mod+Tab'],
  ['tabs.cycle-backward', 'mod+shift+Tab'],
  ['tabs.switch-to-left', 'mod+PageUp'],
  ['tabs.switch-to-right', 'mod+PageDown'],
  ['tabs.switch-to-first', 'mod+1'],
  ['tabs.switch-to-second', 'mod+2'],
  ['tabs.switch-to-third', 'mod+3'],
  ['tabs.switch-to-fourth', 'mod+4'],
  ['tabs.switch-to-fifth', 'mod+5'],
  ['tabs.switch-to-sixth', 'mod+6'],
  ['tabs.switch-to-seventh', 'mod+7'],
  ['tabs.switch-to-eighth', 'mod+8'],
  ['tabs.switch-to-ninth', 'mod+9'],
  ['tabs.switch-to-tenth', 'mod+0'],
  ['file.quick-open', 'mod+P']
])
