name: mac-universe-build

on:
  push:
    branches:
      - master
      - release
      - dev
      - 'cicd/**'

jobs:
  mac-pack: # 打包任务
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: export CSC_IDENTITY_AUTO_DISCOVERY=false
      - run: yarn electron:build --publish=never
      - uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: dist_electron/*.dmg

