name: mac-universe-build

on:
  push:
    branches:
      - master
      - release
      - dev
      - 'cicd/**'

jobs:
  mac-pack: # 打包任务
    runs-on: macos-latest
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: echo $CSC_IDENTITY_AUTO_DISCOVERY
      - run: yarn electron:build --publish=never || true
      - uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: dist_electron/*.dmg

